export type NotificationFrequency = 'daily' | 'weekly';

// Client-side form data (what users submit)
export interface ContentPreferenceFormData {
  prompt: string;
  notificationTime: string; // HH:mm format
  frequency: NotificationFrequency;
  parameters?: Record<string, unknown>;
}

// Server-generated metadata from GPT
export interface ContentMetadata {
  title: string;  // Generated by GPT
  category: string;  // Inferred by GPT from the prompt
}

// Full database model (includes server-side fields)
export interface ContentPreference extends ContentPreferenceFormData, ContentMetadata {
  id: string;
  userId: string;
  lastNotificationAt: string | null;
  createdAt: string;
  updatedAt: string;
  active: boolean;
}
